# Generated by Django 4.2.3 on 2023-10-11 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0003_remove_randevusaatleri_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10, verbose_name='Count')),
            ],
        ),
        migrations.AddField(
            model_name='randevusaatleri',
            name='sira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berberAhmetApp.count', verbose_name='Count'),
        ),
    ]
