# Generated by Django 4.2.3 on 2023-10-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0004_count_randevusaatleri_sira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='count',
            field=models.IntegerField(max_length=10, verbose_name='Count'),
        ),
    ]
