# Generated by Django 4.2.3 on 2023-10-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0005_alter_count_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='count',
            field=models.IntegerField(verbose_name='Count'),
        ),
    ]
