# Generated by Django 4.2.3 on 2023-10-12 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0006_alter_count_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevusaatleri',
            name='dolu_mu',
            field=models.BooleanField(default=False, verbose_name='Dolu mu?'),
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tarih', models.DateTimeField(null=True, verbose_name='Tarih')),
                ('createdAt', models.DateTimeField(auto_now=True, null=True)),
                ('Müsteri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
        ),
    ]
