# Generated by Django 4.2.3 on 2023-10-12 23:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0007_randevusaatleri_dolu_mu_randevu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='about',
        ),
        migrations.AddField(
            model_name='appuser',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
