# Generated by Django 4.2.3 on 2023-10-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0009_randevu_randevusaatleri_alter_appuser_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevu',
            name='randevuSaatleri',
        ),
        migrations.AddField(
            model_name='randevu',
            name='dolu_mu',
            field=models.BooleanField(default=False, verbose_name='Dolu mu?'),
        ),
        migrations.AddField(
            model_name='randevu',
            name='saat',
            field=models.ManyToManyField(to='berberAhmetApp.hours', verbose_name='Saat'),
        ),
        migrations.AddField(
            model_name='randevu',
            name='sira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berberAhmetApp.count', verbose_name='Count'),
        ),
    ]
