# Generated by Django 4.2.3 on 2023-10-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0010_remove_randevu_randevusaatleri_randevu_dolu_mu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevu',
            name='dolu_mu',
        ),
        migrations.AddField(
            model_name='hours',
            name='dolu_mu',
            field=models.BooleanField(default=False, verbose_name='Dolu mu?'),
        ),
    ]
