# Generated by Django 4.2.3 on 2023-10-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0012_rename_sira_randevu_siras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='count',
            field=models.CharField(max_length=10, verbose_name='Count'),
        ),
    ]
