# Generated by Django 4.2.3 on 2023-10-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0015_remove_randevusaatleri_dolu_mu_remove_randevu_saat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randevu',
            old_name='saat',
            new_name='saats',
        ),
        migrations.AlterField(
            model_name='randevu',
            name='siras',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berberAhmetApp.count', verbose_name='Counts'),
        ),
        migrations.AlterField(
            model_name='randevusaatleri',
            name='saat',
            field=models.ManyToManyField(to='berberAhmetApp.hours', verbose_name='Saat'),
        ),
    ]
