# Generated by Django 4.2.3 on 2023-10-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0017_rename_saats_randevu_saat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randevu',
            old_name='saat',
            new_name='r_rs',
        ),
        migrations.RenameField(
            model_name='randevu',
            old_name='siras',
            new_name='r_sayi',
        ),
        migrations.RenameField(
            model_name='randevusaatleri',
            old_name='saati',
            new_name='rs_saat',
        ),
        migrations.RenameField(
            model_name='randevusaatleri',
            old_name='sira',
            new_name='rs_sayi',
        ),
    ]
