# Generated by Django 4.2.3 on 2023-10-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0019_remove_randevu_r_rs_remove_randevu_r_sayi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='count',
            new_name='counts',
        ),
    ]
