# Generated by Django 4.2.3 on 2023-10-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0020_rename_count_count_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='counts',
            field=models.IntegerField(verbose_name='Count'),
        ),
    ]
