# Generated by Django 4.2.3 on 2023-10-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0022_hizmetler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hizmetler',
            name='hizmet',
            field=models.CharField(max_length=20, verbose_name='Hizmet'),
        ),
    ]
