# Generated by Django 4.2.3 on 2023-10-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0023_alter_hizmetler_hizmet'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmetler',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Hizmet Avatar'),
        ),
    ]
