# Generated by Django 4.2.3 on 2023-10-18 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0024_hizmetler_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='hizmet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berberAhmetApp.hizmetler', verbose_name='Hizmet'),
        ),
    ]
