# Generated by Django 4.2.3 on 2023-10-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0025_randevu_hizmet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
