# Generated by Django 4.2.3 on 2023-10-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0028_alter_randevu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='Açıklama'),
        ),
    ]
