# Generated by Django 4.2.3 on 2023-10-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0029_alter_randevu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=40, verbose_name='Şifre'),
        ),
    ]
