# Generated by Django 4.2.6 on 2023-10-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0032_remove_tatil_is_active_remove_tatil_tatil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatil',
            name='tatil',
            field=models.DateField(null=True, unique=True, verbose_name='Tatil'),
        ),
    ]
