# Generated by Django 4.2.6 on 2023-10-26 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0033_alter_tatil_tatil'),
    ]

    operations = [
        migrations.CreateModel(
            name='haftaTatil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gün', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='berberAhmetApp.days', verbose_name='Tatil günü')),
            ],
        ),
    ]
