# Generated by Django 4.2.6 on 2023-12-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0035_iptalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptalinfo',
            name='Tarih',
            field=models.DateTimeField(null=True, verbose_name='Tarih'),
        ),
    ]
