# Generated by Django 4.2.6 on 2023-12-20 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berberAhmetApp', '0039_alter_appuser_first_name_alter_appuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haftatatil',
            name='gün',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='berberAhmetApp.days', verbose_name='Tatil günü'),
        ),
    ]
